/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_protoseo_inputsourceautoconverter_converter_MacNative */

#ifndef _Included_com_protoseo_inputsourceautoconverter_converter_MacNative
#define _Included_com_protoseo_inputsourceautoconverter_converter_MacNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_protoseo_inputsourceautoconverter_converter_MacNative
 * Method:    findSelectableInputSources
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_protoseo_inputsourceautoconverter_converter_MacNative_findSelectableInputSources
  (JNIEnv *, jobject);

/*
 * Class:     com_protoseo_inputsourceautoconverter_converter_MacNative
 * Method:    convert
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_protoseo_inputsourceautoconverter_converter_MacNative_convert
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
